function ok = vsSelfTest(verbose)
%VSSELFTEST Check this Octave build without a fleet.
%   VSSELFTEST() exercises every vs* function against a stub bridge: it
%   confirms each one builds the config_json the box expects, that the
%   argument guards fire, and that vsObservation produces the right
%   observation matrix. No boxes, no network, no Python packages beyond
%   numpy and scipy.
%
%   OK = VSSELFTEST() returns true when everything passed.
%
%   Run it after changing anything here, and after an Octave upgrade.

if nargin < 1; verbose = true; end
here = fileparts(mfilename('fullpath'));
addpath(here);

work = fullfile(tempdir(), 'vs_selftest');
if isfolder(work); rmdir(work, 's'); end
mkdir(work);

stub = fullfile(work, 'stub_bridge.py');
fid = fopen(stub, 'w');
fprintf(fid, '%s\n', ...
 'import json, sys, pathlib', ...
 'argv = sys.argv[1:]', ...
 'if argv and argv[0] == "probe":', ...
 '    print(json.dumps({"reachable": True})); sys.exit(0)', ...
 'def opt(f): return argv[argv.index(f)+1] if f in argv else None', ...
 'raw = pathlib.Path(opt("--config")).read_text()', ...
 'cfg = json.loads(raw)', ...
 'box = next(iter(cfg))', ...
 'rec = {"config": cfg,', ...
 '       "files":   [argv[i+1] for i,x in enumerate(argv) if x == "--file"],', ...
 '       "texts":   [argv[i+1] for i,x in enumerate(argv) if x == "--text"],', ...
 '       "numbers": [argv[i+1] for i,x in enumerate(argv) if x == "--number"]}', ...
 'out = pathlib.Path(opt("--out"))', ...
 'out.with_name("last_config.json").write_text(raw)', ...
 'out.with_name("last_data.json").write_text(json.dumps(rec))', ...
 'import numpy as np, scipy.io as sio', ...
 'sio.savemat(opt("--out"), {"config_json": json.dumps({box: {"status": "done"}}),', ...
 '                           "field_map_json": "{}", "dummy": np.zeros((2,2))})', ...
 'print(json.dumps({"status": "done"}))');
fclose(fid);

cfg = vsConfig('runner', stub, 'workdir', work, 'verbose', false);
pass = 0; fail = 0;

% ---- the wire payload each wrapper builds ------------------------------
    function check(desc, thunk, wantJson)
        try
            thunk();
        catch err
            report(desc, false, ['raised ' err.identifier]); return
        end
        got = strtrim(fileread(fullfile(work, 'last_config.json')));
        report(desc, strcmp(got, wantJson), got);
    end
    function report(desc, good, detail)
        if good; pass = pass + 1; mark = 'ok  '; else; fail = fail + 1; mark = 'FAIL'; end
        if verbose || ~good
            printf('%s %-34s %s\n', mark, desc, detail);
        end
    end
    function checkError(desc, thunk, wantId)
        try
            thunk(); report(desc, false, 'no error raised');
        catch err
            report(desc, strcmp(err.identifier, wantId), err.identifier);
        end
    end

check('clip encodes', @() vsClip(cfg, 'images', 'a.jpg', 'texts', 'a dog'), ...
      '{"clip":{"command":"encode"}}');
check('sbert encodes', @() vsSbert(cfg, 'texts', {'x'}), ...
      '{"sbert":{"command":"encode"}}');
check('lang_sam prompt at section top', ...
      @() vsLangSam(cfg, 'images', 'a.jpg', 'prompt', 'a dog'), ...
      '{"lang_sam":{"text_prompt":["a dog"]}}');
check('tapnext session at section top', ...
      @() vsTapnext(cfg, 'video', 'v.mp4', 'session', 's1'), ...
      '{"tapnext":{"command":"track","session_id":"s1"}}');
check('yolo classes as a JSON array', ...
      @() vsYolo(cfg, 'images', 'a.jpg', 'session', 's1', 'classes', 16), ...
      '{"yolo":{"command":"detect","session_id":"s1","parameters":{"classes":[16]}}}');
check('lightglue session in parameters', ...
      @() vsLightglue(cfg, 'images', 'a.jpg', 'command', 'stream', 'session', 's1'), ...
      '{"lightglue":{"command":"stream","parameters":{"session_id":"s1"}}}');
check('unimatch one-element list stays a list', ...
      @() vsUnimatch(cfg, 'images', {'a','b'}, 'attn_splits_list', 2), ...
      '{"unimatch":{"command":"flow","parameters":{"attn_splits_list":[2]}}}');
check('vggt defaults to reconstruct', @() vsVggt(cfg, 'images', 'a.jpg'), ...
      '{"vggt":{"command":"reconstruct"}}');
check('opencv upper-cases the extractor', ...
      @() vsOpencv(cfg, 'images', {'a','b'}, 'feature_extractor', 'sift'), ...
      '{"opencv":{"command":"match","parameters":{"feature_extractor":"SIFT"}}}');
check('moge passes fov_x', @() vsMoge(cfg, 'images', 'a.jpg', 'fov_x', 60), ...
      '{"moge":{"command":"infer","parameters":{"fov_x":60}}}');
check('features flags survive', @() vsFeatures(cfg, 'images', 'a.jpg', 'draw', false), ...
      '{"features":{"command":"extract","parameters":{"draw":false}}}');
check('open_clip encodes', @() vsOpenClip(cfg, 'texts', 'hi', 'model', 'ViT-B-32'), ...
      '{"open_clip":{"command":"encode","parameters":{"model":"ViT-B-32"}}}');
check('d4rt tracks', @() vsD4rt(cfg, 'video', 'v.mp4'), ...
      '{"d4rt":{"command":"track"}}');
check('pycv eval sends one code string', ...
      @() vsPycv(cfg, 'expr', 'cv2.Canny(vs.image, 100, 200)'), ...
      '{"pycv":{"command":"eval"}}');
check('pycv args ride in the section', ...
      @() vsPycv(cfg, 'expr', '1 + 1', 'args', struct('lo', 50)), ...
      '{"pycv":{"command":"eval","args":{"lo":50}}}');

check('reset, session at section top', @() vsReset(cfg, 'tapnext', 's1'), ...
      '{"tapnext":{"command":"reset","session_id":"s1"}}');
check('reset, session in parameters', @() vsReset(cfg, 'lightglue', 's1'), ...
      '{"lightglue":{"command":"reset","parameters":{"session_id":"s1"}}}');

% ---- the guards --------------------------------------------------------
checkError('clip without texts', @() vsClip(cfg, 'images', 'a.jpg'), 'visionist:clip');
checkError('lang_sam without prompt', @() vsLangSam(cfg, 'images', 'a.jpg'), 'visionist:langSam');
checkError('moge on cpu', @() vsMoge(cfg, 'images', 'a.jpg', 'device', 'cpu'), 'visionist:moge');
checkError('yolo images and video', @() vsYolo(cfg, 'images', 'a', 'video', 'v'), 'visionist:yolo');
checkError('unimatch flow needs 2', @() vsUnimatch(cfg, 'images', 'a.jpg'), 'visionist:unimatch');
checkError('d4rt points out of range', ...
           @() vsD4rt(cfg, 'video', 'v', 'points', [1.5 0.2]), 'visionist:d4rt');
checkError('unknown box', @() vsHost(cfg, 'nope'), 'visionist:unknownBox');
checkError('pycv needs expr or files', @() vsPycv(cfg), 'visionist:pycv');
checkError('pycv expr and files clash', ...
           @() vsPycv(cfg, 'expr', 'x', 'files', {'main.py'}), 'visionist:pycv');

% ---- vsObservation -----------------------------------------------------
s = struct('numFrames', 3, ...
           'frameKpts', {{[10 20; 50 60], [11 21; 51 61], [12 22; 52 62]}}, ...
           'edges', [1 1 2 1; 2 1 3 1; 1 2 2 2; 2 2 3 2]);
b = vsObservation(s);
report('observation: 2 full tracks', ...
       b.stats.nTracksKept == 2 && isequal(size(b.obs_matrix), [6 2]) && ...
       ~any(isnan(b.obs_matrix(:))), mat2str(size(b.obs_matrix)));
report('observation: x column is right', ...
       isequal(b.obs_matrix([1 3 5], 1)', [10 11 12]), ...
       mat2str(b.obs_matrix([1 3 5], 1)'));

g = struct('numFrames', 3, 'frameKpts', {{[10 20], [99 99], [12 22]}}, ...
           'edges', [1 1 3 1]);
bb = vsObservation(g, 'mode', 'backbone');
gg = vsObservation(g, 'mode', 'greedy');
report('observation: backbone bridges a gap', ...
       bb.stats.nTracksKept == 1 && bb.stats.nGappedTracks == 1 && ...
       all(isnan(bb.obs_matrix(3:4, 1))), sprintf('%d track(s)', bb.stats.nTracksKept));
report('observation: greedy does not', gg.stats.nTracksKept == 0, ...
       sprintf('%d track(s)', gg.stats.nTracksKept));

rmdir(work, 's');
printf('\n%d passed, %d failed\n', pass, fail);
ok = (fail == 0);
if nargout == 0; clear ok; end
end
